// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231206173807_Initiali new database")]
    partial class Initialinewdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Shop.Shared.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 12, 6, 18, 38, 7, 662, DateTimeKind.Local).AddTicks(1774),
                            Email = "admin@admin.pl",
                            PasswordHash = new byte[] { 111, 81, 3, 109, 191, 7, 126, 212, 243, 175, 24, 120, 79, 221, 195, 112, 210, 193, 147, 40, 130, 49, 176, 189, 99, 105, 73, 40, 76, 192, 62, 41, 92, 36, 192, 147, 250, 249, 203, 165, 166, 124, 208, 189, 109, 138, 226, 25, 146, 31, 136, 237, 82, 62, 85, 49, 147, 28, 83, 216, 231, 154, 219, 68 },
                            PasswordSalt = new byte[] { 114, 202, 78, 100, 16, 28, 152, 133, 24, 58, 142, 114, 126, 103, 223, 168, 211, 71, 168, 45, 208, 239, 98, 137, 56, 36, 222, 71, 139, 37, 152, 31, 125, 191, 218, 166, 17, 214, 21, 18, 235, 183, 155, 40, 53, 91, 186, 26, 71, 160, 81, 53, 160, 21, 244, 221, 20, 233, 113, 235, 42, 234, 31, 37, 199, 238, 40, 168, 163, 22, 25, 202, 84, 112, 35, 1, 150, 48, 23, 166, 33, 57, 144, 24, 83, 134, 44, 5, 114, 15, 183, 121, 37, 101, 131, 2, 104, 107, 243, 36, 174, 11, 98, 230, 208, 198, 167, 31, 156, 144, 35, 221, 166, 63, 3, 232, 243, 13, 234, 169, 190, 69, 34, 75, 90, 127, 64, 75 },
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.Library.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("pages")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "Dagmar Hackett",
                            genres = "Romance,Criminal,Romance",
                            name = "et cumque",
                            pages = 423
                        },
                        new
                        {
                            id = 2,
                            author = "Orval Tillman",
                            genres = "Horror,Romance,Action",
                            name = "error cupiditate",
                            pages = 1127
                        },
                        new
                        {
                            id = 3,
                            author = "Tyson Hudson",
                            genres = "Comic,Drama,Criminal",
                            name = "placeat qui",
                            pages = 848
                        },
                        new
                        {
                            id = 4,
                            author = "Janessa Botsford",
                            genres = "History,History,Horror",
                            name = "ab non",
                            pages = 323
                        },
                        new
                        {
                            id = 5,
                            author = "Lera Flatley",
                            genres = "Drama,History,Romance",
                            name = "et blanditiis",
                            pages = 206
                        },
                        new
                        {
                            id = 6,
                            author = "Earnestine Sauer",
                            genres = "Comic,Romance",
                            name = "quis beatae",
                            pages = 541
                        },
                        new
                        {
                            id = 7,
                            author = "Chad Grimes",
                            genres = "Horror,Comic,History",
                            name = "omnis veritatis",
                            pages = 221
                        },
                        new
                        {
                            id = 8,
                            author = "Tina Cassin",
                            genres = "Criminal",
                            name = "est ut",
                            pages = 980
                        },
                        new
                        {
                            id = 9,
                            author = "Aidan Gleason",
                            genres = "Drama,Comic",
                            name = "ad officiis",
                            pages = 898
                        },
                        new
                        {
                            id = 10,
                            author = "Griffin Mayert",
                            genres = "Horror,Romance,History",
                            name = "minima aut",
                            pages = 1090
                        },
                        new
                        {
                            id = 11,
                            author = "Golda Jones",
                            genres = "Horror,Criminal",
                            name = "ducimus dolor",
                            pages = 1129
                        },
                        new
                        {
                            id = 12,
                            author = "Wilber Farrell",
                            genres = "Criminal,Drama",
                            name = "neque dicta",
                            pages = 1817
                        },
                        new
                        {
                            id = 13,
                            author = "Zoie Murray",
                            genres = "Romance",
                            name = "corrupti et",
                            pages = 1592
                        },
                        new
                        {
                            id = 14,
                            author = "Maci Gutmann",
                            genres = "Comic,Horror,Criminal",
                            name = "est est",
                            pages = 1613
                        },
                        new
                        {
                            id = 15,
                            author = "Evert Morissette",
                            genres = "Comic",
                            name = "illum repellat",
                            pages = 1740
                        },
                        new
                        {
                            id = 16,
                            author = "Fannie Schoen",
                            genres = "Drama",
                            name = "natus iusto",
                            pages = 1614
                        },
                        new
                        {
                            id = 17,
                            author = "Mckenzie Friesen",
                            genres = "Criminal,Action",
                            name = "quia tempore",
                            pages = 1618
                        },
                        new
                        {
                            id = 18,
                            author = "Neva Robel",
                            genres = "Criminal,Horror,Horror",
                            name = "qui nam",
                            pages = 1855
                        },
                        new
                        {
                            id = 19,
                            author = "May Erdman",
                            genres = "Horror,Action,Romance",
                            name = "occaecati aliquam",
                            pages = 1978
                        },
                        new
                        {
                            id = 20,
                            author = "Gia Krajcik",
                            genres = "History",
                            name = "doloremque officiis",
                            pages = 1506
                        },
                        new
                        {
                            id = 21,
                            author = "Bailee Sanford",
                            genres = "History",
                            name = "et praesentium",
                            pages = 1449
                        },
                        new
                        {
                            id = 22,
                            author = "Orpha Luettgen",
                            genres = "Comic,Criminal",
                            name = "ducimus fugiat",
                            pages = 1989
                        },
                        new
                        {
                            id = 23,
                            author = "Cecilia Kautzer",
                            genres = "Criminal,Drama",
                            name = "est quod",
                            pages = 1476
                        },
                        new
                        {
                            id = 24,
                            author = "Neoma Shields",
                            genres = "Action,Romance,Action",
                            name = "vel sed",
                            pages = 455
                        },
                        new
                        {
                            id = 25,
                            author = "Tad Hodkiewicz",
                            genres = "Comic,Criminal",
                            name = "voluptatem eveniet",
                            pages = 596
                        },
                        new
                        {
                            id = 26,
                            author = "Bradley Murazik",
                            genres = "History",
                            name = "natus ullam",
                            pages = 1679
                        },
                        new
                        {
                            id = 27,
                            author = "Savannah Beier",
                            genres = "Romance,Criminal",
                            name = "nobis quae",
                            pages = 385
                        },
                        new
                        {
                            id = 28,
                            author = "Tina Lehner",
                            genres = "History,Romance,Comic",
                            name = "porro in",
                            pages = 742
                        },
                        new
                        {
                            id = 29,
                            author = "Cleve Rogahn",
                            genres = "Criminal,Romance",
                            name = "placeat rerum",
                            pages = 438
                        },
                        new
                        {
                            id = 30,
                            author = "Doug Kuhn",
                            genres = "Romance",
                            name = "dolor dicta",
                            pages = 389
                        },
                        new
                        {
                            id = 31,
                            author = "Keenan Gleichner",
                            genres = "Romance,History,History",
                            name = "quos quia",
                            pages = 1462
                        },
                        new
                        {
                            id = 32,
                            author = "Mireya Kunze",
                            genres = "Action",
                            name = "minus unde",
                            pages = 359
                        },
                        new
                        {
                            id = 33,
                            author = "Camren Reichel",
                            genres = "Action",
                            name = "voluptatem quo",
                            pages = 654
                        },
                        new
                        {
                            id = 34,
                            author = "Berniece Funk",
                            genres = "History,History",
                            name = "cum et",
                            pages = 80
                        },
                        new
                        {
                            id = 35,
                            author = "Daisy Kozey",
                            genres = "History,Action",
                            name = "labore est",
                            pages = 947
                        },
                        new
                        {
                            id = 36,
                            author = "Carroll Daugherty",
                            genres = "Comic,Criminal,Comic",
                            name = "dolores cumque",
                            pages = 1020
                        },
                        new
                        {
                            id = 37,
                            author = "Lorna Kling",
                            genres = "Comic",
                            name = "rem voluptatem",
                            pages = 717
                        },
                        new
                        {
                            id = 38,
                            author = "Lelah Hauck",
                            genres = "Action,History,History",
                            name = "natus corrupti",
                            pages = 906
                        },
                        new
                        {
                            id = 39,
                            author = "Hollis Hilpert",
                            genres = "Romance,Comic,History",
                            name = "dolorem at",
                            pages = 450
                        },
                        new
                        {
                            id = 40,
                            author = "Jarrett Kertzmann",
                            genres = "Drama,Action,Comic",
                            name = "eaque id",
                            pages = 1065
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
