// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231128132155_Security Update")]
    partial class SecurityUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Shop.Shared.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("P06Shop.Shared.Library.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("pages")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "Dagmar Hackett",
                            genres = "Drama,Romance",
                            name = "et cumque",
                            pages = 423
                        },
                        new
                        {
                            id = 2,
                            author = "Orval Tillman",
                            genres = "Criminal",
                            name = "error cupiditate",
                            pages = 1127
                        },
                        new
                        {
                            id = 3,
                            author = "Tyson Hudson",
                            genres = "History",
                            name = "placeat qui",
                            pages = 848
                        },
                        new
                        {
                            id = 4,
                            author = "Janessa Botsford",
                            genres = "Criminal,Action,Criminal",
                            name = "ab non",
                            pages = 323
                        },
                        new
                        {
                            id = 5,
                            author = "Lera Flatley",
                            genres = "Romance,Romance",
                            name = "et blanditiis",
                            pages = 206
                        },
                        new
                        {
                            id = 6,
                            author = "Earnestine Sauer",
                            genres = "Horror,History",
                            name = "quis beatae",
                            pages = 541
                        },
                        new
                        {
                            id = 7,
                            author = "Chad Grimes",
                            genres = "Criminal",
                            name = "omnis veritatis",
                            pages = 221
                        },
                        new
                        {
                            id = 8,
                            author = "Tina Cassin",
                            genres = "Romance,Horror",
                            name = "est ut",
                            pages = 980
                        },
                        new
                        {
                            id = 9,
                            author = "Aidan Gleason",
                            genres = "Criminal",
                            name = "ad officiis",
                            pages = 898
                        },
                        new
                        {
                            id = 10,
                            author = "Griffin Mayert",
                            genres = "Romance",
                            name = "minima aut",
                            pages = 1090
                        },
                        new
                        {
                            id = 11,
                            author = "Golda Jones",
                            genres = "Criminal,Comic,History",
                            name = "ducimus dolor",
                            pages = 1129
                        },
                        new
                        {
                            id = 12,
                            author = "Wilber Farrell",
                            genres = "Criminal,Horror",
                            name = "neque dicta",
                            pages = 1817
                        },
                        new
                        {
                            id = 13,
                            author = "Zoie Murray",
                            genres = "Comic",
                            name = "corrupti et",
                            pages = 1592
                        },
                        new
                        {
                            id = 14,
                            author = "Maci Gutmann",
                            genres = "Horror,Action",
                            name = "est est",
                            pages = 1613
                        },
                        new
                        {
                            id = 15,
                            author = "Evert Morissette",
                            genres = "Drama,Horror,Criminal",
                            name = "illum repellat",
                            pages = 1740
                        },
                        new
                        {
                            id = 16,
                            author = "Fannie Schoen",
                            genres = "Drama,Action,Horror",
                            name = "natus iusto",
                            pages = 1614
                        },
                        new
                        {
                            id = 17,
                            author = "Mckenzie Friesen",
                            genres = "History,Criminal",
                            name = "quia tempore",
                            pages = 1618
                        },
                        new
                        {
                            id = 18,
                            author = "Neva Robel",
                            genres = "Comic",
                            name = "qui nam",
                            pages = 1855
                        },
                        new
                        {
                            id = 19,
                            author = "May Erdman",
                            genres = "Romance,Comic,History",
                            name = "occaecati aliquam",
                            pages = 1978
                        },
                        new
                        {
                            id = 20,
                            author = "Gia Krajcik",
                            genres = "Romance,Comic",
                            name = "doloremque officiis",
                            pages = 1506
                        },
                        new
                        {
                            id = 21,
                            author = "Bailee Sanford",
                            genres = "Romance,Criminal",
                            name = "et praesentium",
                            pages = 1449
                        },
                        new
                        {
                            id = 22,
                            author = "Orpha Luettgen",
                            genres = "Action,Horror",
                            name = "ducimus fugiat",
                            pages = 1989
                        },
                        new
                        {
                            id = 23,
                            author = "Cecilia Kautzer",
                            genres = "Action",
                            name = "est quod",
                            pages = 1476
                        },
                        new
                        {
                            id = 24,
                            author = "Neoma Shields",
                            genres = "Criminal",
                            name = "vel sed",
                            pages = 455
                        },
                        new
                        {
                            id = 25,
                            author = "Tad Hodkiewicz",
                            genres = "History,Comic",
                            name = "voluptatem eveniet",
                            pages = 596
                        },
                        new
                        {
                            id = 26,
                            author = "Bradley Murazik",
                            genres = "Romance",
                            name = "natus ullam",
                            pages = 1679
                        },
                        new
                        {
                            id = 27,
                            author = "Savannah Beier",
                            genres = "Horror",
                            name = "nobis quae",
                            pages = 385
                        },
                        new
                        {
                            id = 28,
                            author = "Tina Lehner",
                            genres = "Criminal",
                            name = "porro in",
                            pages = 742
                        },
                        new
                        {
                            id = 29,
                            author = "Cleve Rogahn",
                            genres = "History",
                            name = "placeat rerum",
                            pages = 438
                        },
                        new
                        {
                            id = 30,
                            author = "Doug Kuhn",
                            genres = "Action",
                            name = "dolor dicta",
                            pages = 389
                        },
                        new
                        {
                            id = 31,
                            author = "Keenan Gleichner",
                            genres = "Romance",
                            name = "quos quia",
                            pages = 1462
                        },
                        new
                        {
                            id = 32,
                            author = "Mireya Kunze",
                            genres = "Drama,History",
                            name = "minus unde",
                            pages = 359
                        },
                        new
                        {
                            id = 33,
                            author = "Camren Reichel",
                            genres = "Comic,Romance,Romance",
                            name = "voluptatem quo",
                            pages = 654
                        },
                        new
                        {
                            id = 34,
                            author = "Berniece Funk",
                            genres = "Horror",
                            name = "cum et",
                            pages = 80
                        },
                        new
                        {
                            id = 35,
                            author = "Daisy Kozey",
                            genres = "Romance,Comic,Criminal",
                            name = "labore est",
                            pages = 947
                        },
                        new
                        {
                            id = 36,
                            author = "Carroll Daugherty",
                            genres = "Drama",
                            name = "dolores cumque",
                            pages = 1020
                        },
                        new
                        {
                            id = 37,
                            author = "Lorna Kling",
                            genres = "Drama,Comic,History",
                            name = "rem voluptatem",
                            pages = 717
                        },
                        new
                        {
                            id = 38,
                            author = "Lelah Hauck",
                            genres = "History,Criminal,Romance",
                            name = "natus corrupti",
                            pages = 906
                        },
                        new
                        {
                            id = 39,
                            author = "Hollis Hilpert",
                            genres = "Horror,Comic,Drama",
                            name = "dolorem at",
                            pages = 450
                        },
                        new
                        {
                            id = 40,
                            author = "Jarrett Kertzmann",
                            genres = "Action,Romance",
                            name = "eaque id",
                            pages = 1065
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
